version: 2

formats:
  - pdf
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - plantuml
  jobs:
    post_build:
      - python docs/sources/check_arb.py
    post_install:
      - python docs/sources/check_arb.py
      - python docs/sources/generate_doxygen_api.py
      - python docs/sources/check_arb.py

sphinx:
   configuration: docs/sources/conf.py
   builder: html

python: 
  install:
    - requirements: docs/requirements.txt
  system_packages: true
    