verison: 2

formats:
  - pdf
  - htmlzip

build:
  os: "ubuntu-22.04"
  tools:
    python: 
      version: "3.10"
  jobs:
    post_install:
      - echo "Test Pre Build jobs"
      - python -m docs/sources/generate_doxygen_api

sphinx:
   configuration: docs/sources/conf.py
   builder: html

python: 
  install:
    - method: pip
    - requirements: docs/requirements.txt
  system_packages: true
    