verison: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: 
      version: "3.8"
  jobs:
    post_install:
      - echo "Test Pre Build jobs"
      - python -m docs/sources/generate_doxygen_api

python: 
  version: "3.8"
  install:
    - requirements: docs/requirements.txt
    - method: pip