version: 2

formats:
  - pdf
  - htmlzip

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
    - plantuml
  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
    post_build:
      - echo "Command run at 'post_build' step"
      - echo `date`
    post_install:
      - echo "Test Pre Build jobs"
      - python docs/sources/generate_doxygen_api.py

sphinx:
   configuration: docs/sources/conf.py
   builder: html

python: 
  install:
    - requirements: docs/requirements.txt
  system_packages: true
    