verison: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: 
      version: "3.10"
  jobs:
    post_install:
      - echo "Test Pre Build jobs"
      - python -m docs/sources/generate_doxygen_api

sphinx:
   configuration: docs/sources/conf.py

python: 
  install:
    - method: pip
    - requirements: docs/requirements.txt
    